export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';

export const FETCH_MOVIE_REQUEST = 'FETCH_MOVIE_REQUEST';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_FAILURE = 'FETCH_MOVIE_FAILURE';

export const CREATE_MOVIE_REQUEST = 'CREATE_MOVIE_REQUEST';
export const CREATE_MOVIE_SUCCESS = 'CREATE_MOVIE_SUCCESS';
export const CREATE_MOVIE_FAILURE = 'CREATE_MOVIE_FAILURE';

export const FETCH_DIRECTORS_REQUEST = 'FETCH_DIRECTORS_REQUEST';
export const FETCH_DIRECTORS_SUCCESS = 'FETCH_DIRECTORS_SUCCESS';
export const FETCH_DIRECTORS_FAILURE = 'FETCH_DIRECTORS_FAILURE';

export const FETCH_DIRECTOR_REQUEST = 'FETCH_DIRECTOR_REQUEST';
export const FETCH_DIRECTOR_SUCCESS = 'FETCH_DIRECTOR_SUCCESS';
export const FETCH_DIRECTOR_FAILURE = 'FETCH_DIRECTOR_FAILURE';

export const CREATE_DIRECTOR_REQUEST = 'CREATE_DIRECTOR_REQUEST';
export const CREATE_DIRECTOR_SUCCESS = 'CREATE_DIRECTOR_SUCCESS';
export const CREATE_DIRECTOR_FAILURE = 'CREATE_DIRECTOR_FAILURE';

